### ISSUE TITLE
Fix MIT license violations

### ISSUE THREAD

**Issue by ch4ot1c** [anonymousbitcoin/anon#11]
Hello,

I notice files like:
https://github.com/anonymousbitcoin/anon/commit/825325591cf5f69086b2f801708b7e40def72525#diff-7116ef0705885343c9e1b2171a06be0eL1
https://github.com/anonymousbitcoin/anon/commit/f1181ccf5ad8f683b9a1d3c80a7665f6ffa759f2#diff-c949f93d03f44a4217d7a138f9e2e54aR2
and
https://github.com/anonymousbitcoin/anon/blob/a1f96b6da113a80d0d09ece437d234a32511b9d3/COPYING#L1

have the 'Anon' copyright entry, but are sometimes missing the 'Bitcoin Private' (or Zcash, Bitcoin Core) entry. Please fix this, kindly.

**Comment by kaypon** [comment]
Hey Ch4ot1c,

Thanks for pointing out this issue. We've reinserted BTCP copyright entries which we're accidentally overwritten, and will continue looking to make sure we reinsert any others which might have gotten overlooked during development. As an open source project we take proper citation seriously, and thank you for your own contributions to the ecosystem. Feel free to let us know if we're still missing anything after the next day or so as we continue combing everything.

**Comment by ch4ot1c** [comment]
Thanks! Take your time.
