### ISSUE TITLE
Problems with Blockchain sync

### ISSUE THREAD

**Issue by acabamar** [anonymousbitcoin/anon#110]
I've been with the 93% blockchain for several weeks, a few days ago they sent me some coins through Tradesatoshi, but they are not in my wallet. How can I solve that.

This issue tracker is only for technical issues related to anond.

General Anonymous Bitcoin questions and/or support requests and are best directed to the [ANON Github Repo](https://github.com/anonymousbitcoin/anon/issues).

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of ANON you were using:
Run `anond --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.anon/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.anon` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.anon` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by ZE4L0T** [comment]
You need to update your wallet.
Tech help is available at 
Telegram - https://t.me/anontechnicalsupport
or
Discord - https://discord.gg/4mDACW2
