### ISSUE TITLE
Adding apt-get update and apt-get upgrade to the building instructions

### ISSUE THREAD

**Issue by darthcrypto87** [anonymousbitcoin/anon#27]
In the build instructions for the full node, and later in the Masternode guide, there should be added that you should run

sudo apt-get update
sudo apt-get upgrade

before installing the dependencies. Otherwise you'll get the following error message, especially on a fresh VPS:

"E: Failed to fetch http://lon1.mirrors.digitalocean.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-131.157_amd64.deb  404  Not Found [IP: 5.101.111.50 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"

When updating and upgrading before you install the dependencies you don't run into any errors.

**Comment by kaypon** [comment]
Hello @darthcrypto87, thanks for the additional suggestion. This will also be added to the repo, and I will close out this issue when its made its way into master.

Thanks again for your suggestion.

**Comment by kaypon** [comment]
Closing this. Please see PR #33
