### ISSUE TITLE
./anonutil/build.sh -j$(nproc) causes problems but can be dealt with leaving away -j$(nproc)

### ISSUE THREAD

**Issue by darthcrypto87** [anonymousbitcoin/anon#29]
To avoid problems and support requests for this issue you might add to the Readme the following:

Checkout
git clone https://github.com/anonymousbitcoin/anon.git
cd anon

Build
./anonutil/build.sh -j$(nproc)

**In case you get errors while compiling use this command instead
./anonutil/build.sh**

Fetch Zcash ceremony keys
./anonutil/fetch-params.sh

**Comment by kaypon** [comment]
Hi @darthcrypto87, we have added this to a separate branch (`miners-testnet`). 

We will close this issue after the changes have been merged into master, which we expect will be very soon.

Thank you for your suggestion.

**Comment by kaypon** [comment]
Closing this. Please see PR #33
