### ISSUE TITLE
Gradle Issues

### ISSUE THREAD

**Issue by brentanon** [anonymousbitcoin/anon#30]
I tried building that full node wallet but can't get further than running this command ./gradlew clean fatJar it tells me Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

- DK808 on discord

**Comment by thomasluis** [comment]
<img width="836" alt="screen shot 2018-08-21 at 5 51 53 pm" src="https://user-images.githubusercontent.com/32315791/44431168-06dc8880-a56b-11e8-8a9b-d5adc2bd5913.png">
@brentanon Can you give us a further description of the issue?
