### ISSUE TITLE
[NODE] anond launch error: boost::mutex::~mutex(): Assertion `!res' failed

### ISSUE THREAD

**Issue by rewrewby** [anonymousbitcoin/anon#50]
Ubuntu 16.04

Compiled on 4 different servers and the same error on anond launch:
```anond: /home/anon/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/mutex.hpp:111: boost::mutex::~mutex(): Assertion `!res' failed.
Aborted```

**Comment by nlevo** [comment]
Closing this issue due to lack of user response. If the issue is still a problem, feel free to reopen this ticket.
