### ISSUE TITLE
anond compilation for Mac: libevent library is also needed.

### ISSUE THREAD

**Issue by fabioganga** [anonymousbitcoin/anon#61]
Hi devs,

Please notice that when compiling anon for Mac on the latest High Sierra build (10.13.6) it does complain that libevent is not installed.

Running the command

> brew install libevent

is required for the compilation to proceed.

Please considering adding libevent to the read me file.

Thank you.

**Comment by nlevo** [comment]
A pull-request (https://github.com/anonymousbitcoin/anon/pull/62) has been created.
