### ISSUE TITLE
COMPILING ON MAC HIGH SIERRA FAILS WITH LATEST BUILD PROTOCOL 180005

### ISSUE THREAD

**Issue by fabioganga** [anonymousbitcoin/anon#70]
### Describe the issue
Although compiling anon did work fine in the past and no change occurred in my High Sierra 10.13.6, with the latest git pull for the protocol update it returns the error highlighted below.

### Can you reliably reproduce the issue?

1. Git pull to update the local anon to the latest commits
2. Run the /.anonutil/build-mac.sh 

### Expected behaviour
Unless now there are different libraries to install that I am unaware of, the build should compile just fine as it used to do.

### Actual behaviour + errors
Building Boost.Build engine with toolset darwin... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
make: *** [/Users/fabio/anon/depends/work/build/x86_64-apple-darwin17.7.0/boost/1_62_0-9f20f2abf0e/./.stamp_configured] Error 1

### The version of ANON you were using:
Run `anond --version` to find out

### Machine specs:
- High Sierra 10.13.6
- CPU: Intel i7 
- RAM: 4GB  
- Disk size:  70Gb /emulated)
- Disk Type HD 
- Linux kernel version (uname -a):  macos.shared 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

- Compiler version (gcc -version): 

onfigured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Thanks!

**Comment by nlevo** [comment]
I wasn't able to reproduce the same error on High Sierra 10.13.6. 
Try to reset: 
```
git fetch origin
git checkout master
git reset --hard origin/master
make clean
./anonutil/build-mac.sh
```

**Comment by fabioganga** [comment]
Thanks @nlevo for the answer!

The problem unfortunately persists:

> 
macos:~ fabio$ cd anon/
macos:anon fabio$ git fetch origin
macos:anon fabio$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
macos:anon fabio$ git reset --hard origin/master
HEAD is now at 541c67c97 Merge pull request #67 from anonymousbitcoin/fix/seeders
macos:anon fabio$ make clean
make: *** No rule to make target `clean'.  Stop.
macos:anon fabio$ ./anonutil/build-mac.sh
echo Configuring boost...
Configuring boost...
rm -rf /Users/fabio/anon/depends/x86_64-apple-darwin17.7.0; mkdir -p /Users/fabio/anon/depends/x86_64-apple-darwin17.7.0/lib; cd /Users/fabio/anon/depends/x86_64-apple-darwin17.7.0; 
mkdir -p /Users/fabio/anon/depends/work/build/x86_64-apple-darwin17.7.0/boost/1_62_0-9f20f2abf0e/.
cd /Users/fabio/anon/depends/work/build/x86_64-apple-darwin17.7.0/boost/1_62_0-9f20f2abf0e/.;     PKG_CONFIG_LIBDIR=/Users/fabio/anon/depends/x86_64-apple-darwin17.7.0/lib/pkgconfig PKG_CONFIG_PATH=/Users/fabio/anon/depends/x86_64-apple-darwin17.7.0/share/pkgconfig PATH=/Users/fabio/anon/depends/x86_64-apple-darwin17.7.0/native/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin   ./bootstrap.sh --without-icu --with-libraries=chrono,filesystem,program_options,system,thread,test
Building Boost.Build engine with toolset darwin... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
make: *** [/Users/fabio/anon/depends/work/build/x86_64-apple-darwin17.7.0/boost/1_62_0-9f20f2abf0e/./.stamp_configured] Error 1
macos:anon fabio$ 

Any other suggestion you have for me, please?

Thanks

**Comment by fabioganga** [comment]
Thanks so much @nlevo for the suggestion!

At last I have made it!

Have a great day and thanks again, much appreciated buddy!

Kind Regards, Fabio
