### ISSUE TITLE
Hosted anon masternode on gincoin does not receive the start alias command from windowsx64 wallet. 

### ISSUE THREAD

**Issue by nknarula** [anonymousbitcoin/anon#76]
This issue tracker is only for technical issues related to anond.

General Anonymous Bitcoin questions and/or support requests and are best directed to the [ANON Github Repo](https://github.com/anonymousbitcoin/anon/issues).

### Describe the issue

Created the masternode on p.ginplatform.io

#### If so, please list the steps to reproduce below:
1. Try to start a masternode on the ginplatform
2. They never get the command
3. Seems to me someone forgot to code the push

### Expected behaviour
Tell us what should happen

The masternode hosting site should receive a start alias or start missing command when I push the buttons in the java GUI wallet.

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of ANON you were using:
Run `anond --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.anon/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.anon` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.anon` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by nknarula** [comment]
Goes without saying it’s the current version of the wallet, the same version ginplatform is using. I spent a while troubleshooting it with them yesterday and can forward the entire conversation in an email if necessary.

**Comment by thomasluis** [comment]
it seems like this issue is related to the gin platform, not Anon core. Closing this issue. If you feel you need more assistance, seek help in our tech-support channel on [Discord](https://discord.gg/9XQMspU)
